// Generated by CoffeeScript 1.4.0
(function() {
  var NewTaskController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NewTaskController = (function(_super) {

    __extends(NewTaskController, _super);

    NewTaskController.prototype.events = {
      "tap a[data-action=save]": "onSave"
    };

    NewTaskController.prototype.elements = {
      "#txt-titulo": "titulo",
      "#txt-descripcion": "descripcion"
    };

    function NewTaskController() {
      NewTaskController.__super__.constructor.apply(this, arguments);
    }

    NewTaskController.prototype.onSave = function(event) {
      __Model.Task.create({
        titulo: this.titulo.val(),
        descripcion: this.descripcion.val()
      });
      Lungo.Router.back();
      this.titulo.val("");
      return this.descripcion.val("");
    };

    return NewTaskController;

  })(Monocle.Controller);

  __Controller.NewTask = new NewTaskController("section#new");

}).call(this);
