// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.Task = (function(_super) {

    __extends(Task, _super);

    function Task() {
      return Task.__super__.constructor.apply(this, arguments);
    }

    Task.prototype.container = "section#task article ul";

    Task.prototype.template = "<li class=\"{{^done}}red{{/done}}\">\n  <a href=\"#\">\n    {{#done}}\n    <div class=\"right bubble blue\">Hecho</div>\n    {{/done}}\n\n    <strong>{{titulo}}</strong>\n    <small>{{descripcion}}</small>\n  </a>\n</li>";

    Task.prototype.events = {
      "tap li": "onTap"
    };

    Task.prototype.onTap = function(event) {
      this.model.updateAttributes({
        done: true
      });
      return this.refresh();
    };

    return Task;

  })(Monocle.View);

}).call(this);
